### ISSUE TITLE
Interested in moving typst npm package to @typst-community

### ISSUE THREAD

**Issue by jcbhmr** [typst-community/.github#1]
Hello! 👋

I'm interested in putting the https://www.npmjs.com/package/typst under this @typst-community organization. Is this organization active? Was the name claimed just to claim it? Can I add other Typst-related projects to it? Is it open to community projects? Is it just a dumping ground for your projects? Is it supposed to exist? Is it open to more members?

Anyway with all those questions, here's more info on the https://www.npmjs.com/package/typst npm package:
1. It's source code is here: https://github.com/jcbhmr/typst.js
2. It lets you do `npx typst` to run the CLI distributed through npm.
3. It uses a `postinstall` script to download the appropriate `typst` binary from the official Releases page on GitHub.
4. Each version of the npm package is locked to a specific version of Typst (currently `0.10.0`)
5. There's also a rudimentary JavaScript API that currently exposes only a single `compile(src, dest)` function.
6. It includes `.d.ts` TypeScript types.
7. The README.md of the project is a copy of the Typst official project's README and needs to be updated.

<sub>P.S. I'd also like turn over control of the https://www.npmjs.com/package/typst npm package name to @typst or @typst-community or something as well as the https://www.npmjs.com/org/typst npm organization.</sub>

cc @huwaireb since I notice [you are not watching this repository](https://github.com/typst-community/.github/watchers)

**Comment by huwaireb** [comment]
Hey 👋, glad to see someone finally stumble on this organization. The name was free at the time so I thought i'd claim it for the future typst community members to be able to serve as a purpose similar to @coq-community, @elm-community or @nix-community.

For your questions:
**1. Is this organization active?**
No, i'm the only member so far and have not been able to put much time into the org despite earlier motivations
**2. Was the name claimed just to claim it?**
Yes and No, it's with good intent as in the end its for the community.
**3. Can I add other Typst-related projects to it?**
Yes, you can. I'll extend an invite if you are interested.
**4. Is it open to community projects?**
Again, yes.
**5. Is it just a dumping ground for your projects?**
Not only mine, but also the communities.
**6. Is it supposed to exist?**
Yes, it'll be needed sooner or later, there was no harm setting it up till people showed interest like this.
**7. Is it open to more members?**
Yep, again if you would like to join the organization I'll send an invite.

You're free to transfer `typst.js` onto this organization once you join. Regarding the official npm organization, it might be better at the hands of the official Typst team. 

To distribute `typst.js` in npm, a new typst-community npm org could be created and it'll be under there.

**Comment by jcbhmr** [comment]
Thanks for very nicely and concisely answering my questions! 😊

> Hey 👋, glad to see someone finally stumble on this organization. The name was free at the time so I thought i'd claim it for the future typst community members to be able to serve as a purpose similar to https://github.com/coq-community, https://github.com/elm-community or https://github.com/nix-community.

👍

> You're free to transfer typst.js onto this organization once you join.

Awesome! ❤️

<details><summary>You're right I do need permission to create the repo lol</summary>

![image](https://github.com/typst-community/.github/assets/61068799/91652eca-6d5d-4d63-a1be-20b041acf643)

</details>

> Regarding the typst npm organization, it might be better at the hands of the official Typst team.

Good idea! I'm not sure how open the @typst organization is to taking on _more things_ but I'll open an Issue. https://github.com/typst/typst/issues/2946

> To distribute typst.js in npm, a new typst-community npm org could be created and it'll be under there.

<details><summary>✅ Done!</summary>

![image](https://github.com/typst-community/.github/assets/61068799/a4ac513f-94a1-4c8a-a43a-109ba080e434)

</details>

Do you have an npm username that I can add/hand-over the https://www.npmjs.com/org/typst-community to? (it's not https://www.npmjs.com/~huwaireb since that's a 404)

---

related things on @typst official stance on _more things_:
https://github.com/typst/typst/pull/2933 where npm `typst` deemed out-of-scope for core
https://github.com/typst/typst/pull/767 where installer `curl | sh` script deemed out-of-scope for core.

👆 this is why IMO a centralized community-style organization like this is a good idea: centralize the community projects that are too "out-there" to get official backing 👍👍

**Comment by huwaireb** [comment]
> Sure! Sounds cool!

Invite Extended 

> Do you have an npm username that I can add/hand-over the [npmjs.com/org/typst-community]

Should be there now. 

> related things on @typst official stance on _more things_: [typst/typst#2933](https://github.com/typst/typst/pull/2933) where npm `typst` deemed out-of-scope for core [typst/typst#767](https://github.com/typst/typst/pull/767) where installer `curl | sh` script deemed out-of-scope for core.
> 
> 👆 this is why IMO a centralized community-style organization like this is a good idea: centralize the community projects that are too "out-there" to get official backing 👍👍

Certainly, glad you also see it that way.

**Comment by jcbhmr** [comment]
✅ Accepted invite & transferred to https://github.com/typst-community/typst.js

<details><summary>📩 npm organization invite sent 👍</summary>

![image](https://github.com/typst-community/.github/assets/61068799/dfbc0d73-d767-43e2-9136-ccd90107dca1)

looks like you accepted; you're now an "owner" too of the npm @typst-community org 👍

![image](https://github.com/typst-community/.github/assets/61068799/a3ba6f51-bdd3-48fc-bcea-b0e43f147afc)

</details>

closing this issue since the outcome was achieved. Thanks for your timely & helpful responses! 🙏
